---
 - name: Be sure /etc/rc.conf.d exist
   file: path=/etc/rc.conf.d/ state=directory owner=root group=wheel mode=0655

 - name: Be sure Motd exist
   template: src=motd.j2 dest=/etc/motd  

 - name: Be sure pkgng repository is configured
   template: src=pkg.conf.j2 dest=/usr/local/etc/pkg.conf

 - name: Be sure sudo is installed
   pkgng: name=sudo state=present

 - name: Be sure sudo is configured
   copy: src=sudoers dest=/usr/local/etc/sudoers validate='visudo -cf %s'

 - name: Be sure usefull tools are installed
   pkgng: name={{ item }} state=present
   with_items:
     - screen
     - bash
