---
 - name: Be sure each Jail are created
   ezjail: name={{ hostvars[item]['name'] }} ip_addr={{ hostvars[item]['ip']  }} disktype=zfs
   with_items: jails_hosted

 - name: Be sure /usr/local/etc is present in each jail
   file: path={{ jails_dir }}/{{ hostvars[item]['name'] }}/usr/local/etc state=directory owner=root group=wheel
   with_items: jails_hosted

 - name: Be sure pkgng configuration is present in each jail
   template: src=pkg.conf.j2 dest={{ jails_dir }}/{{ hostvars[item]['name'] }}/usr/local/etc/pkg.conf
   with_items: jails_hosted

 - fetch: src=/etc/resolv.conf dest=/tmp/ansible

 - name: Be sure resolv.conf is present in each jail
   template: src=/tmp/ansible/{{ inventory_hostname  }}/etc/resolv.conf dest={{ jails_dir }}/{{ hostvars[item]['name'] }}/etc/resolv.conf
   with_items: jails_hosted

 - name: Be sure rc.conf is configured in each jail
   template: src=rc.conf.j2 dest={{ jails_dir }}/{{ hostvars[item]['name'] }}/etc/rc.conf
   with_items: jails_hosted

 - name: Be sure ezjail is started
   service: name=ezjail state=restarted
