---
 - name: Create ZFS partition for jails
   zfs: name={{ jails_zfs_root }} mountpoint={{ jails_dir }} checksum={{ zfs_checksum }} state=present

 - name: Configure network interface for jails
   template: src=network.j2 dest=/etc/rc.conf.d/network
   notify: restart network

 - include: ezjail.yml

 - include: create_jails.yml
